### ISSUE TITLE
Error double response

### ISSUE THREAD

**Issue by asger777** [devslopes-learn/mac-chat-api#16]
When i send post request to account/register with already registered account, it crashes

![image](https://user-images.githubusercontent.com/23039633/31354422-71e9c0f6-ad47-11e7-8d84-70c0e8992244.png)

**Comment by njsnx** [comment]
Yeah this is happening to me too - very annoying

**Comment by danielesposito** [comment]
same here. makes this api very useless. in many social apps users will once or twice use an email thats already been registered. Having your api crash renders this service useless. On top of that, developer seems to be not very responsive.

**Comment by jburgoyn** [comment]
Hey guys, so this API was created for the sole purpose of teaching how to interact with an API in the scope of what is taught in the Devslopes courses. Not necessarily be a commercially ready chat API. Not every user interaction was taken into consideration since that would be out of the scope of the project. That being said, we encourage the students to clone the project and make any improvements they would like to! Happy coding!

**Comment by anm8tr** [comment]
Not sure why they didn't design the course with an emphasis on commercial application, how about Parse/AWS or Firebase etc.
